#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:nil broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:nil todo:t |:t
#+TITLE: The Minecraft Tourist
#+DATE: <2018-08-23>
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)

Minecraft's majestic vistas have long captivated Internet message-boards and social media.
At the same time, advanced image captioning software based on deep learning techniques can give sophisticated, content-aware descriptions of an image.
These systems are trained with and meant for photographs of the real world, and often do poorly in video game domains (for example, describing any screenshot as being "video game" with high probability---not wrong, but not helpful!)
 
In this assignment, you will be training a recurrent convolutional neural network to caption images from Minecraft screenshots, identifying trees, mountains, and other biome features as well as enemies.

In this assignment you will:

- Implement a recurrent CNN in TensorFlow
- Create additional screenshots to explore your algorithm's generalization performance
- Compare against a general-purpose image captioning system of your choice

The goal of this assignment is for you to understand:

- Where data for captioning systems can come from
- How to process image data and textual data in a joint framework
- The implicit assumptions behind approaches to solving specific commonsense problems

The starting point for this assignment is a dataset of Minecraft screenshots of /generated worlds/ which were synthesized specifically for this purpose, along with textual captions ("I'm standing in the desert and I see a creeper") generated by a context-free grammar which also drove the world generation and camera positioning process.
You are encouraged to tweak the grammar and/or world generation program to expand the dataset and improve your generalization performance.
